default: &default
  adapter: postgresql
  user: midnight
  encoding: utf8
  password: 18891914
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: activemile_development

test:
  <<: *default
  database: activemile_test

production:
  <<: *default
  database: activemile_production
